{% set name = "pytest-codspeed" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_codspeed-{{ version }}.tar.gz
  sha256: 0adc24baf01c64a6ca0a0b83b3cd704351708997e09ec086b7776c32227d4e0a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - cffi >=1.15.1
    - pytest >=3.8
    - filelock >=3.12.2
    - setuptools

test:
  imports:
    - pytest_codspeed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CodSpeedHQ/pytest-codspeed
  summary: Pytest plugin to create CodSpeed benchmarks
  dev_url: https://github.com/CodSpeedHQ/pytest-codspeed
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
