{% set name = "pytest-codspeed" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_codspeed-{{ version }}.tar.gz
  sha256: 0e9af08ca93ad897b376771db92693a81aa8990eecc2a778740412e00a6f6eaf

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]

requirements:
  host:
    - python
    - hatchling
    - pip
    - setuptools >=61
    - cffi >=1.17.1
  run:
    - python
    - cffi >=1.17.1
    - setuptools  # [py>=312]
    - pytest >=3.8
    - filelock >=3.12.2
    - rich >=13.8.1
    - importlib-metadata >=8.5.0  # [py<310]
  build:
    - {{ compiler('c') }}
  run_constrained:
    - pytest-benchmark >=5.0.0,<5.1.dev0
    - pytest-xdist >=3.6.1,<3.7.dev0

test:
  imports:
    - pytest_codspeed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://codspeed.io/
  summary: Pytest plugin to create CodSpeed benchmarks
  description: pytest-codspeed is a pytest plugin that integrates with CodSpeed to benchmark and monitor the performance of Python code.
  dev_url: https://github.com/CodSpeedHQ/pytest-codspeed
  doc_url: https://docs.codspeed.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - kenodegard
