{% set name = "pytest-codspeed" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_codspeed-{{ version }}.tar.gz
  sha256: c5b80100ea32dd44079bb2db298288763eb8fe859eafa1650a8711bd2c32fd06

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - cffi >=1.17.1
    - setuptools # [py>=312]
    - pytest >=3.8
    - filelock >=3.12.2
    - rich >=13.8.1
    - importlib-metadata >=8.5.0 # [py<310]

test:
  imports:
    - pytest_codspeed
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://codspeed.io/
  summary: Pytest plugin to create CodSpeed benchmarks
  description: pytest-codspeed is a pytest plugin that integrates with CodSpeed to benchmark and monitor the performance of Python code.
  dev_url: https://github.com/CodSpeedHQ/pytest-codspeed
  doc_url: https://docs.codspeed.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - kenodegard
